services:

  directus:
    image: directus/directus:11.1.1
    ports:
      - 8055:8055
    volumes:
      - ./directus/database:/directus/database
      - ./directus/uploads:/directus/uploads
      - ./directus/extensions:/directus/extensions
    env_file:
      - ./env/directus.env

  react:
    build:
      context: ./dockerfiles
      dockerfile: react.dockerfile
    ports:
      - 3000:3000
    env_file:
      - ./env/react.env
    volumes:
      - ./react:/app
      

  flask:
    build:
      context: ./dockerfiles
      dockerfile: flask.dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./flask:/app
    env_file:
      - ./env/flask.env
    depends_on:
      - directus

  nginx:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - react